
# Primary's ingestion port
primaryMainPort: &primaryMainPort 8000
# Primary's replication port
primaryReplicationPort: &primaryReplicationPort 8001
# Replica's search port
replicaMainPort: &replicaMainPort 8002
# Replica's replication port
replicaReplicationPort: &replicaReplicationPort 8003

# nrtsearch-primary's configs
primary:
  command: ["bash", "-c"]
  args: ["/user/app/configs/start_primary.sh"]
  # count of primary instances
  count: 1
  config:
    path: /user/app/configs/
  stateDir: "/user/app/primary_state"
  indexDir: "/user/app/primary_index_base"
  archiveDir: "/user/app/primary_index_archiver"
  ports:
    deployment:
      - name: main-port
        containerPort: *primaryMainPort
        protocol: TCP
      - name: rep-port
        containerPort: *primaryReplicationPort
        protocol: TCP
    service:
      - name: main-port
        protocol: TCP
        port: *primaryMainPort
        targetPort: *primaryMainPort
      - name: rep-port
        protocol: TCP
        port: *primaryReplicationPort
        targetPort: *primaryReplicationPort
  service:
    type: ClusterIP

# nrtsearch-replica's configs
replica:
  command: ["bash", "-c"]
  args: ["/user/app/configs/start_replica.sh"]
  # count of replica instances
  count: 1
  config:
    path: /user/app/configs/
  stateDir: "/user/app/replica_state"
  indexDir: "/user/app/replica_index_base"
  archiveDir: "/user/app/replica_index_archiver"
  ports:
    deployment:
      - name: main-port
        containerPort: *replicaMainPort
        protocol: TCP
      - name: rep-port
        containerPort: *replicaReplicationPort
        protocol: TCP
    service:
      - name: main-port
        protocol: TCP
        port: *replicaMainPort
        targetPort: *replicaMainPort
      - name: rep-port
        protocol: TCP
        port: *replicaReplicationPort
        targetPort: *replicaReplicationPort
  service:
    type: ClusterIP

# nrtsearch-client is a long running pod which is useful to interact with nrtsearch-primary and nrtsearch-replica pods
client:
  # Whether to launch the nrtsearch-client pod or not. Assign "enabled: false" to not launch the pod on startup of the instance
  enabled: true
  command: ["bash", "-c"]
  args: ["sleep 3600"]
  count: 1
  config:
    path: /user/app/configs/

# Explore mode is the quick-test mode when you want to quickly deploy nrtsearch with test index created and started.
# Enabling this mode mounts test data and configs in all nrtsearch pods.
#  This mode can be disabled by assigning the updating the following "enabled: false"
exploreNrtsearchMode:
  enabled: true
  # name of the test index
  testIndexName: "testIdx"

# nrtsearch docker image
image:
  repository: nrtsearch-dev-user
  tag: latest
  pullPolicy: IfNotPresent
