language: java
install: true
dist: bionic

jdk:
  - oraclejdk14

services:
  - docker

script:
  - ./gradlew clean check test --info
  - ./gradlew clean buildGrpcGateway
  - ./gradlew clean installDist :test -PincludePerfTests=* --tests "com.yelp.nrtsearch.server.YelpReviewsTest.runYelpReviews" --info
  - ./gradlew clean installDist :test -PincludePerfTests=* --tests "com.yelp.nrtsearch.server.grpc.MergeBehaviorTests" --info
