version: '3.7'

services:

  primary-node:
    build: ./
    container_name: primary-node
    command: /user/app/build/install/nrtsearch/bin/lucene-server
    hostname: primary-node
    volumes:
      - 'myshare:/shared'

  replica-node:
    build: ./
    command: /user/app/build/install/nrtsearch/bin/lucene-server
    hostname: replica-node
    deploy:
      replicas: 3
    volumes:
      - 'myshare:/shared'

#  grpc-gateway:
#    build: ./grpc-gateway
#    container_name: grpc-gateway
#    command: /user/app/build/install/nrtsearch/bin/lucene-server
#    hostname: grpc-gateway
#    volumes:
#      - 'myshare:/shared'

volumes:
  myshare:
    driver: local

