nodeName: "node-name-replica"
hostName: "host-name-replica"
port: "8002"
replicationPort: "8003"
stateDir: "/user/app/replica_state"
indexDir: "/user/app/replica_index_base"
threadPoolConfiguration:
  search:
    maxThreads: 16
  index:
    maxThreads: 4
botoCfgPath: "/user/app/boto.cfg"
bucketName: "nrtsearch-bucket"
serviceName: "nrtsearch-service-test"
downloadAsStream: "true"