# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle for v0.x branch

on:
  push:
    branches: [ v0.x ]
  pull_request:
    branches: [ v0.x ]

jobs:
  build:
    uses: Yelp/nrtsearch/.github/workflows/gradle.yml@v0.x
    with:
      branch: v0.x
      badge_branch: badge_v0.x
